{% set name = "numkit" %}
{% set version = "1.2.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/numkit-{{ version }}.tar.gz
  sha256: 903ed05e06146736f35ebd8c630be85423b5a61fc7fa842e6a8f81413f1fe99b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - numpy >=1.9
    - scipy >=1.0
    - six

test:
  imports:
    - numkit
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Becksteinlab/numkit
  summary: Numerical first aid kit (with numpy/scipy).
  doc_url: https://numkit.readthedocs.io/
  dev_url: https://github.com/Becksteinlab/numkit
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - orbeckst
    - njzjz
