{% set name = "numkit" %}
{% set version = "1.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/numkit-{{ version }}.tar.gz
  sha256: 41d928028c8ba3a64438da2c72b8b644c67bb4b61dafe9b258395ce22c6ac921

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.9
  run:
    - python >=3.9
    - numpy >=1.9
    - scipy >=1.0

test:
  imports:
    - numkit
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Becksteinlab/numkit
  summary: Numerical first aid kit (with numpy/scipy).
  doc_url: https://numkit.readthedocs.io/
  dev_url: https://github.com/Becksteinlab/numkit
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - njzjz
    - orbeckst
